[package]
name = "tsak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
rhai = "1.16.2"
rhai-rand = "0.1.5"
rhai-sci = "0.2.0"
tokio = "1.32.0"
zenoh = "0.10.0-rc"
